version: "3.3"

networks:
    lumen:

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "lumen-app"
        restart: unless-stopped
        volumes:
            - ./src:/var/www/html/
            - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        networks:
            - lumen
        ports:
            - "8080:80"
    db:
        image: mysql:5.7.29
        container_name: "lumen-db"
        restart: unless-stopped
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        networks:
            - lumen
        ports:
            - "3306:3306"
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - lumen
    artisan:
        image: php:7.4
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db
            - app
        networks:
            - lumen
        entrypoint: ["/var/www/html/artisan"]
